title: Vikas Singh Saini
author:
  name: Vikas Singh Saini
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  I write my thoughts here.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: auto
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: instagram,      user_url: "https://www.instagram.com/vikasdeepsinghsaini" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/vikasofvikas" }
    - { platform: twitter,        user_url: "https://twitter.com/vikasofvikas" }
    - { platform: youtube,        user_url: "https://www.youtube.com/channel/UCT4QSW9dMPzN5cxdv6dcNKw" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
